[package]
name = "wrfm"
version = "0.5.0"
edition.workspace = true
description = "A parser for .wrfm 3D wireframe models"
readme = "README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords = ["cli", "tui", "file"]
categories = ["command-line-utilities"]

[dependencies]

[features]
default = ["std"]
std = []
